// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package router

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockController
func (_mock *MockController) Create(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockController_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockController_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockController_Expecter) Create(w interface{}, r interface{}) *MockController_Create_Call {
	return &MockController_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *MockController_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockController_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_Create_Call) Return() *MockController_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_Create_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockController_Create_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type MockController
func (_mock *MockController) GetByID(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockController_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockController_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockController_Expecter) GetByID(w interface{}, r interface{}) *MockController_GetByID_Call {
	return &MockController_GetByID_Call{Call: _e.mock.On("GetByID", w, r)}
}

func (_c *MockController_GetByID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockController_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_GetByID_Call) Return() *MockController_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_GetByID_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockController_GetByID_Call {
	_c.Run(run)
	return _c
}

// Healthz provides a mock function for the type MockController
func (_mock *MockController) Healthz(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockController_Healthz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Healthz'
type MockController_Healthz_Call struct {
	*mock.Call
}

// Healthz is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockController_Expecter) Healthz(w interface{}, r interface{}) *MockController_Healthz_Call {
	return &MockController_Healthz_Call{Call: _e.mock.On("Healthz", w, r)}
}

func (_c *MockController_Healthz_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockController_Healthz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_Healthz_Call) Return() *MockController_Healthz_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_Healthz_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockController_Healthz_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function for the type MockController
func (_mock *MockController) List(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockController_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockController_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockController_Expecter) List(w interface{}, r interface{}) *MockController_List_Call {
	return &MockController_List_Call{Call: _e.mock.On("List", w, r)}
}

func (_c *MockController_List_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockController_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_List_Call) Return() *MockController_List_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_List_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockController_List_Call {
	_c.Run(run)
	return _c
}

// Statusz provides a mock function for the type MockController
func (_mock *MockController) Statusz(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockController_Statusz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Statusz'
type MockController_Statusz_Call struct {
	*mock.Call
}

// Statusz is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockController_Expecter) Statusz(w interface{}, r interface{}) *MockController_Statusz_Call {
	return &MockController_Statusz_Call{Call: _e.mock.On("Statusz", w, r)}
}

func (_c *MockController_Statusz_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockController_Statusz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_Statusz_Call) Return() *MockController_Statusz_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockController_Statusz_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockController_Statusz_Call {
	_c.Run(run)
	return _c
}
