// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/javiertlopez/awesome/model"
	mock "github.com/stretchr/testify/mock"
)

// Delivery is an autogenerated mock type for the Delivery type
type Delivery struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Delivery) GetByID(ctx context.Context, id string) (model.Video, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Video
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Video); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Video)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
