// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/javiertlopez/awesome/model"
	mock "github.com/stretchr/testify/mock"
)

// Ingestion is an autogenerated mock type for the Ingestion type
type Ingestion struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, anyVideo
func (_m *Ingestion) Create(ctx context.Context, anyVideo model.Video) (model.Video, error) {
	ret := _m.Called(ctx, anyVideo)

	var r0 model.Video
	if rf, ok := ret.Get(0).(func(context.Context, model.Video) model.Video); ok {
		r0 = rf(ctx, anyVideo)
	} else {
		r0 = ret.Get(0).(model.Video)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Video) error); ok {
		r1 = rf(ctx, anyVideo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
