// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/javiertlopez/awesome/model"
)

// Delivery is an autogenerated mock type for the Delivery type
type Delivery struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Delivery) GetByID(ctx context.Context, id string) (model.Video, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Video
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Video); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Video)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function for the List method with pagination
func (_m *Delivery) List(ctx context.Context, page, limit int) ([]model.Video, error) {
	ret := _m.Called(ctx, page, limit)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]model.Video), ret.Error(1)
}

type mockConstructorTestingTNewDelivery interface {
	mock.TestingT
	Cleanup(func())
}

// NewDelivery creates a new instance of Delivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDelivery(t mockConstructorTestingTNewDelivery) *Delivery {
	mock := &Delivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
