// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/javiertlopez/awesome/model"
)

// Ingestion is an autogenerated mock type for the Ingestion type
type Ingestion struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, anyVideo
func (_m *Ingestion) Create(ctx context.Context, anyVideo model.Video) (model.Video, error) {
	ret := _m.Called(ctx, anyVideo)

	var r0 model.Video
	if rf, ok := ret.Get(0).(func(context.Context, model.Video) model.Video); ok {
		r0 = rf(ctx, anyVideo)
	} else {
		r0 = ret.Get(0).(model.Video)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Video) error); ok {
		r1 = rf(ctx, anyVideo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIngestion interface {
	mock.TestingT
	Cleanup(func())
}

// NewIngestion creates a new instance of Ingestion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIngestion(t mockConstructorTestingTNewIngestion) *Ingestion {
	mock := &Ingestion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
