// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"

	"github.com/javiertlopez/awesome/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDelivery creates a new instance of MockDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelivery {
	mock := &MockDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDelivery is an autogenerated mock type for the Delivery type
type MockDelivery struct {
	mock.Mock
}

type MockDelivery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelivery) EXPECT() *MockDelivery_Expecter {
	return &MockDelivery_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockDelivery
func (_mock *MockDelivery) GetByID(ctx context.Context, id string) (model.Video, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Video, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Video); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Video)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDelivery_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDelivery_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockDelivery_Expecter) GetByID(ctx interface{}, id interface{}) *MockDelivery_GetByID_Call {
	return &MockDelivery_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDelivery_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockDelivery_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDelivery_GetByID_Call) Return(video model.Video, err error) *MockDelivery_GetByID_Call {
	_c.Call.Return(video, err)
	return _c
}

func (_c *MockDelivery_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Video, error)) *MockDelivery_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDelivery
func (_mock *MockDelivery) List(ctx context.Context, page int, limit int) ([]model.Video, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Video, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []model.Video); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Video)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDelivery_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDelivery_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
//   - page
//   - limit
func (_e *MockDelivery_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *MockDelivery_List_Call {
	return &MockDelivery_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *MockDelivery_List_Call) Run(run func(ctx context.Context, page int, limit int)) *MockDelivery_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDelivery_List_Call) Return(videos []model.Video, err error) *MockDelivery_List_Call {
	_c.Call.Return(videos, err)
	return _c
}

func (_c *MockDelivery_List_Call) RunAndReturn(run func(ctx context.Context, page int, limit int) ([]model.Video, error)) *MockDelivery_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngestion creates a new instance of MockIngestion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestion(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestion {
	mock := &MockIngestion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestion is an autogenerated mock type for the Ingestion type
type MockIngestion struct {
	mock.Mock
}

type MockIngestion_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestion) EXPECT() *MockIngestion_Expecter {
	return &MockIngestion_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIngestion
func (_mock *MockIngestion) Create(ctx context.Context, anyVideo model.Video) (model.Video, error) {
	ret := _mock.Called(ctx, anyVideo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Video
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Video) (model.Video, error)); ok {
		return returnFunc(ctx, anyVideo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Video) model.Video); ok {
		r0 = returnFunc(ctx, anyVideo)
	} else {
		r0 = ret.Get(0).(model.Video)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Video) error); ok {
		r1 = returnFunc(ctx, anyVideo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIngestion_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIngestion_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - anyVideo
func (_e *MockIngestion_Expecter) Create(ctx interface{}, anyVideo interface{}) *MockIngestion_Create_Call {
	return &MockIngestion_Create_Call{Call: _e.mock.On("Create", ctx, anyVideo)}
}

func (_c *MockIngestion_Create_Call) Run(run func(ctx context.Context, anyVideo model.Video)) *MockIngestion_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Video))
	})
	return _c
}

func (_c *MockIngestion_Create_Call) Return(video model.Video, err error) *MockIngestion_Create_Call {
	_c.Call.Return(video, err)
	return _c
}

func (_c *MockIngestion_Create_Call) RunAndReturn(run func(ctx context.Context, anyVideo model.Video) (model.Video, error)) *MockIngestion_Create_Call {
	_c.Call.Return(run)
	return _c
}
